services:
  ### 키키하이 도커 이미지
  spring:
    image: kikihi/server:latest
    container_name: kkh-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend-bridge

  # mysql 이미지
  mysql:
    image: mysql:8.0
    container_name: leets-blog-mysql
    ports:
      - '${MYSQL_PORT}:3306'
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/02-schema.sql
      - ./mysql/valid.sql:/docker-entrypoint-initdb.d/03-valid.sql

    command: --default-authentication-plugin=mysql_native_password
