
name: leets-blog 테스트 CI 파이프라인

### develop으로 PR 올릴 때, 테스트 코드를 실행하여, 체크하는 로직을 수행한다.

on:
  pull_request:
    branches: ["develop"]

jobs:
  #1. Test 용
  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      checks: write
      pull-requests: write

    steps:
      # 1. repository checkout
      - uses: actions/checkout@v4

      # 2. jdk 환경 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 2. gradle 환경 설치
      - name: Gradle Wrapper 권한 부여
        run: chmod +x gradlew

      # 4. gradle 환경 설치
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      # 5. 빌드
      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test


      # 6. JUnit 테스트 결과 게시
#      - name: Test 결과 출력
#        uses: EnricoMi/publish-unit-test-result-action@v2
#        if: always()
#        with:
#          junit_files: '**/build/test-results/test/TEST-*.xml'
#          github_token: ${{ secrets.GITHUB_TOKEN }}
